djangouniversity/djangouniversity/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

djangouniversity/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view()),
]

djangouniversity/library/urls.py
from django.urls import path
from . import views

app_name = 'library'
urlpatterns = [

    path('', views.MainView.as_view(), name='all'),
    # path('book/<int:pk>', views.BookCreateView.as_view(), name='ad_detail'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book_detail'),
    path('book/create', views.BookCreateView.as_view(), name='book_create'),
    path('book/<int:pk>/update',
         views.BookUpdateView.as_view(), name='book_update'),
    path('book/<int:pk>/delete',
         views.BookDeleteView.as_view(), name='book_delete'),
    path('book_picture/<int:pk>', views.stream_file, name='book_picture'),
    path('language/', views.LanguageView.as_view(), name='language_list'),
    path('language/create/', views.LanguageCreateView.as_view(), name='language_create'),
    path('language/<int:pk>/update', views.LanguageUpdateView.as_view(), name='language_Update'),
    path('language/<int:pk>/delete', views.LanguageDeleteView.as_view(), name='language_Delete'),
    path('place/', views.PlaceView.as_view(), name='place_list'),
    path('place/create/', views.PlaceCreateView.as_view(), name='place_create'),
    path('place/<int:pk>/update', views.PlaceUpdateView.as_view(), name='place_Update'),
    path('place/<int:pk>/delete', views.PlaceDeleteView.as_view(), name='place_Delete'),
    path('category/', views.CategoryView.as_view(), name='category_list'),
    path('category/create/', views.CategoryCreateView.as_view(), name='category_create'),
    path('category/<int:pk>/update', views.CategoryUpdateView.as_view(), name='category_Update'),
    path('category/<int:pk>/delete', views.CategoryDeleteView.as_view(), name='category_Delete'),
    path('author/', views.AuthorView.as_view(), name='author_list'),
    path('author/create/', views.AuthorCreateView.as_view(), name='author_create'),
    path('author/<int:pk>/update', views.AuthorUpdateView.as_view(), name='author_Update'),
    path('author/<int:pk>/delete', views.AuthorDeleteView.as_view(), name='author_Delete'),

]

djangouniversity/library/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from django.conf import settings


class Author(models.Model):
    name = models.CharField(max_length=200)
    birth = models.DateTimeField()
    death = models.DateTimeField(null=True, blank=True)

    # books = models.ManyToManyField('Books', through='Authored')

    def __str__(self):
        return self.name


class Authored(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE)
    author = models.ForeignKey('Author', on_delete=models.CASCADE)


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Language(models.Model):
    language = models.CharField(max_length=100)

    def __str__(self):
        return self.language


class Place(models.Model):
    section = models.CharField(max_length=100)
    shelf = models.CharField(max_length=50)

    def __str__(self):
        return self.section


class Book(models.Model):
    name = models.CharField(max_length=200,
                            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")])
    publish_day = models.DateTimeField(auto_now_add=True, null=True)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    # author = models.ManyToManyField('Author', through='Authored')
    author = models.ForeignKey('Author', on_delete=models.CASCADE)
    description = models.TextField()
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    place = models.ForeignKey('Place', on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True)
    picture = models.BinaryField(null=True, editable=True)
    # picture = models.BinaryField(null=True, blank=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, help_text='The MIMEType of the file')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                              related_name='book_owner')

    def __str__(self):
        return self.name

djangouniversity/library/forms.py
from library.models import Language, Place, Category, Author, Book
from djangouniversity import settings
from django import forms
from library.humanize import naturalsize
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.exceptions import ValidationError
from django.core import validators


# Create the form class.
class LanguageForm(forms.ModelForm):
    class Meta:
        model = Language
        fields = '__all__'


class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = '__all__'


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class AuthorForm(forms.ModelForm):
    birth = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
    death = forms.DateField(required=False)

    class Meta:
        model = Author
        fields = '__all__'


class BookForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= ' + max_upload_limit_text)
    upload_field_name = 'picture'

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = Book
        fields = ['name', 'author', 'description', 'language', 'place', 'category', 'picture']
        # fields = ['name', 'description', 'picture']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        book = cleaned_data.get('picture')
        if book is None:
            return
        if len(book) > self.max_upload_limit:
            self.add_error('picture', "File must be < " + self.max_upload_limit_text + " bytes")

        # Convert uploaded File object to a picture

    def save(self, commit=True):
        instance = super(BookForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture  # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()
            self.save_m2m()
        return instance
    # Convert uploaded File object to a picture

djangouniversity/library/views.py
from typing import Dict

from django.http import HttpResponse
from django.views import View
from django.urls import reverse_lazy
from .models import Book, Author, Category, Place, Language
from .forms import BookForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db.models import Q, QuerySet


class MainView(View):
    template_name = 'library/book_list.html'

    def get(self, request):

        strval = request.GET.get("search", False)
        if strval:
            query = Q(name__icontains=strval)
            query.add(Q(description__icontains=strval), Q.OR)
            book_list = Book.objects.filter(query).select_related().order_by('-updated_at')[:10]
        else:
            book_list = Book.objects.all().order_by('-updated_at')[:10]

        # Augment the post_list
        for obj in book_list:
            obj.natural_updated = naturaltime(obj.updated_at)
        # print(connection.queries)
        lb = Book.objects.all()
        la = Author.objects.count()
        ctx = {'book_list': book_list, 'search': strval, 'author_count': la}
        return render(request, self.template_name, ctx)
        # print(connection.queries)


class BookListView(ListView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('library:all')


class BookCreateView(OwnerCreateView):
    model = Book

    fields = ['name', 'category', 'description']
    template_name = 'library/book_form.html'
    success_url = reverse_lazy('library:all')

    def get(self, request, pk=None):
        form = BookForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = BookForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

            # Add owner to the model before saving
        book = form.save(commit=False)
        book.owner = self.request.user
        book.save()
        # form.save_m2m()    # Add this
        return redirect(self.success_url)


class BookUpdateView(OwnerUpdateView):
    template_name = 'library/book_form.html'
    model = Book
    # fields = '__all__'
    success_url = reverse_lazy('library:all')

    def get(self, request, pk):
        book = get_object_or_404(Book, id=pk)
        form = BookForm(instance=book)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        book = get_object_or_404(Book, id=pk)
        # , owner=self.request.user)
        form = BookForm(request.POST, request.FILES or None, instance=book)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        book = form.save(commit=False)
        book.save()
        # form.save_m2m()    # Add this

        return redirect(self.success_url)


class BookDeleteView(DeleteView):
    model = Book
    fields = fields = '__all__'
    success_url = reverse_lazy('library:all')


class BookDetailView(OwnerDetailView):
    model = Book
    template_name = "library/book_detail.html"

    def get(self, request, pk):
        x = Book.objects.get(id=pk)
        # comments = Comment.objects.filter(ad=x).order_by('-updated_at')
        # comment_form = CommentForm()
        context = {'book': x}
        return render(request, self.template_name, context)


class LanguageView(View):
    def get(self, request):
        ml = Language.objects.all()
        ctx = {'language_list': ml}
        return render(request, 'library/language_list.html', ctx)


class LanguageCreateView(CreateView):
    model = Language
    fields = '__all__'
    success_url = reverse_lazy('library:all')


class LanguageUpdateView(UpdateView):
    model = Language
    fields = '__all__'
    success_url = reverse_lazy('library:all')


class LanguageDeleteView(DeleteView):
    model = Language
    fields = '__all__'
    success_url = reverse_lazy('library:all')


class PlaceView(View):
    def get(self, request):
        pl = Place.objects.all()
        ctx = {'place_list': pl}
        return render(request, 'library/place_list.html', ctx)


class PlaceCreateView(CreateView):
    model = Place
    fields = '__all__'
    success_url = reverse_lazy('library:all')


class PlaceUpdateView(UpdateView):
    model = Place
    fields = '__all__'
    success_url = reverse_lazy('library:all')


class PlaceDeleteView(DeleteView):
    model = Place
    fields = '__all__'
    success_url = reverse_lazy('library:all')


class CategoryView(View):
    def get(self, request):
        cl = Category.objects.all()
        ctx = {'category_list': cl}
        return render(request, 'library/category_list.html', ctx)


class CategoryCreateView(CreateView):
    model = Category
    fields = '__all__'
    success_url = reverse_lazy('library:all')


class CategoryUpdateView(UpdateView):
    model = Category
    fields = '__all__'
    success_url = reverse_lazy('library:all')


class CategoryDeleteView(DeleteView):
    model = Category
    fields = '__all__'
    success_url = reverse_lazy('library:all')


class AuthorView(View):
    def get(self, request):
        al = Author.objects.all()
        ctx = {'author_list': al}
        return render(request, 'library/author_list.html', ctx)


class AuthorCreateView(CreateView):
    model = Author
    fields = '__all__'
    success_url = reverse_lazy('library:all')


class AuthorUpdateView(UpdateView):
    model = Author
    fields = '__all__'
    success_url = reverse_lazy('library:all')


class AuthorDeleteView(DeleteView):
    model = Author
    fields = '__all__'
    success_url = reverse_lazy('library:all')


class BookDetailView(DetailView):
    model = Book
    template_name = "library/book_detail.html"


def stream_file(request, pk):
    book = get_object_or_404(Book, id=pk)
    response = HttpResponse()
    response['Content-Type'] = book.content_type
    response['Content-Length'] = len(book.picture)
    response.write(book.picture)
    return response

djangouniversity/library/templates/library/author_form.html
{% extends "base_menu.html" %}


{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'library:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

djangouniversity/library/templates/library/author_list.html
{% extends "base_menu.html" %}

{% block content %}
  <h1>Author List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
          {{ author.name }}
         (<a href="{% url 'library:author_Update' author.id %}">Update</a> |
          <a href="{% url 'library:author_Delete' author.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no author in the library.</p>
  {% endif %}
  <p><a href="{% url 'library:author_create' %}">Add a author</a></p>
  <p>
    <a href="{% url 'library:all' %}">Back to books</a>
  </p>
{% endblock %}

djangouniversity/library/templates/library/book_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete book</h1>

<p>Are you sure you want to delete the book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

djangouniversity/library/templates/library/book_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}
{% block content %}
{% if book.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'library:book_picture' book.id %}">
</div>
{% endif %}
<span style="float: right;">
({{ book.name}})

<a href="{% url 'library:book_update' book.id %}"> Update<i class="fa fa-pencil"></i></a>
<a href="{% url 'library:book_delete' book.id %}">Delete<i class="fa fa-trash"></i></a>

</span>
<h1>{{ book.name }}</h1>
{% if book.content_type %}
<img style="float:right; max-width:50%;" src="{% url 'library:book_picture' book.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
{% endif %}
<p>
{{ book.description }}
</p>
<p>
</p>
<p>
<a href="{% url 'library:all' %}">All books</a>
</p>
{% endblock %}

djangouniversity/library/templates/library/book_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'library:all' %}';return false;">
  </form>
</p>
<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});

</script>
{% endblock %}

djangouniversity/library/templates/library/category_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Category</h1>

<p>Are you sure you want to delete the category: {{ category }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

djangouniversity/library/templates/library/category_form.html
{% extends "base_menu.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'library:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

djangouniversity/library/templates/library/category_list.html
{% extends "base_menu.html" %}

{% block content %}
  <h1>category List</h1>
  {% if category_list %}
  <ul>
    {% for category in category_list %}
      <li>
          {{ category.name }}
         (<a href="{% url 'library:category_Update' category.id %}">Update</a> |
          <a href="{% url 'library:category_Delete' category.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no category in the library.</p>
  {% endif %}
  <p><a href="{% url 'library:category_create' %}">Add a category</a></p>
  <p>
    <a href="{% url 'library:all' %}">Back to books</a>
  </p>
{% endblock %}

djangouniversity/library/templates/library/language_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Language</h1>

<p>Are you sure you want to delete the language: {{ language }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

djangouniversity/library/templates/library/language_form.html
{% extends "base_menu.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'library:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

djangouniversity/library/templates/library/language_list.html
{% extends "base_menu.html" %}
{% block content %}
  <h1>Language List</h1>
  {% if language_list %}
  <ul>
    {% for languege in language_list %}
      <li>
          {{ languege.language }}
         (<a href="{% url 'library:language_Update' languege.id %}">Update</a> |
          <a href="{% url 'library:language_Delete' languege.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no language in the library.</p>
  {% endif %}
  <p><a href="{% url 'library:language_create' %}">Add a language</a></p>
  <p>
    <a href="{% url 'library:all' %}">Back to books</a>
  </p>
{% endblock %}

djangouniversity/library/templates/library/place_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Place</h1>

<p>Are you sure you want to delete the place: {{ place }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

djangouniversity/library/templates/library/place_form.html
{% extends "base_menu.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'library:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

djangouniversity/library/templates/library/place_list.html
{% extends "base_menu.html" %}

{% block content %}
  <h1>Place List</h1>
  {% if place_list %}
  <ul>
    {% for place in place_list %}
      <li>
          {{ place.section }}
         (<a href="{% url 'library:place_Update' place.id %}">Update</a> |
          <a href="{% url 'library:place_Delete' place.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no place in the library.</p>
  {% endif %}
  <p><a href="{% url 'library:place_create' %}">Add a place</a></p>
  <p>
    <a href="{% url 'library:all' %}">Back to books</a>
  </p>
{% endblock %}