djangouniversity/djangouniversity/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

djangouniversity/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view()),
]

djangouniversity/library/urls.py
from django.urls import path
from . import views

app_name = 'library'
urlpatterns = [

    path('', views.MainView.as_view(), name='all'),
    # path('book/<int:pk>', views.BookCreateView.as_view(), name='ad_detail'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book_detail'),
    path('book/create', views.BookCreateView.as_view(), name='book_create'),
    path('book/<int:pk>/update',
         views.BookUpdateView.as_view(), name='book_update'),
    path('book/<int:pk>/delete',
         views.BookDeleteView.as_view(), name='book_delete'),
    path('book_picture/<int:pk>', views.stream_file, name='book_picture'),
    path('language/', views.LanguageView.as_view(), name='language_list'),
    path('language/create/', views.LanguageCreateView.as_view(), name='language_create'),
    path('language/<int:pk>/update', views.LanguageUpdateView.as_view(), name='language_Update'),
    path('language/<int:pk>/delete', views.LanguageDeleteView.as_view(), name='language_Delete'),
    path('place/', views.PlaceView.as_view(), name='place_list'),
    path('place/create/', views.PlaceCreateView.as_view(), name='place_create'),
    path('place/<int:pk>/update', views.PlaceUpdateView.as_view(), name='place_Update'),
    path('place/<int:pk>/delete', views.PlaceDeleteView.as_view(), name='place_Delete'),
    path('category/', views.CategoryView.as_view(), name='category_list'),
    path('category/create/', views.CategoryCreateView.as_view(), name='category_create'),
    path('category/<int:pk>/update', views.CategoryUpdateView.as_view(), name='category_Update'),
    path('category/<int:pk>/delete', views.CategoryDeleteView.as_view(), name='category_Delete'),
    path('author/', views.AuthorView.as_view(), name='author_list'),
    path('author/create/', views.AuthorCreateView.as_view(), name='author_create'),
    path('author/<int:pk>/update', views.AuthorUpdateView.as_view(), name='author_Update'),
    path('author/<int:pk>/delete', views.AuthorDeleteView.as_view(), name='author_Delete'),

]

djangouniversity/home/views.py
from django.shortcuts import render

from django.views import View
from django.conf import settings


# Create your views here.

class HomeView(View):
    def get(self, request):
        print(request.get_host())
        host = request.get_host()
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed': settings.INSTALLED_APPS,
            'islocal': islocal
        }
        return render(request, 'home/main.html', context)

djangouniversity/home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>

<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- Replace this value (42-42) with the one provided by the autograder -->

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2022-09-01">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

djangouniversity/home/templates/base_menu.html
{% extends "base_bootstrap.html" %}
{% block navbar %}

<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
    </div>

    <ul class="nav navbar-nav">
        {% url 'librarysss' as library %}
        <li {% if request.get_full_path == library %}class="active"{% endif %}>
            <a href="{% url 'library:all' %}">Books</a></li>

        <ul class="nav navbar-nav navbar-right">

            <li>
                <a href="{% url 'library:book_create' %}">Create Book</a>
            </li>
             <li>
                <a href="{% url 'library:author_create' %}">Create Author</a>
            </li>
            <li>
                <a href="{% url 'library:language_create' %}">Create Language</a>
            </li>
             <li>
                <a href="{% url 'library:place_create' %}">Create Place</a>
            </li>
             <li>
                <a href="{% url 'library:category_create' %}">Create Category</a>
            </li>
            <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle">

                </a>
                <ul class="dropdown-menu">
                    <li>{% url 'library:all' %}>Logout</li>
                </ul>
            </li>



        </ul>
    </ul>
  </div>>
</nav>
{% endblock %}